### ISSUE TITLE
Delay after setting actionbarextras properties

### ISSUE THREAD

**Issue by grazianogrespan** [ricardoalcocer/actionbarextras#91]
Hi! 
Don't know if it is a module issue or my module implementation that creates this glitch.
Every time, just after the app starts, there is little delay in which the actionBar applies my configurations. 
I have set a red background color inside the window's "open" event .
At first, the action bar is black, then background color changes to red only half second later.
Both emulator and device reproduce this effect.

**Comment by manumaticx** [comment]
Hi @grazianogrespan 

yes this is how it works, you're not doing anything wrong. The reason for the delay is the timing until the open event gets fired on the window. This is a Titanium limitation since you cannot access the activity of a window before the open event got fired.

If you are just using this for changing the actionbars background color, you should workaround this by using themes to style your actionbar. If you need to change it at runtime, then you could use this module.

**Comment by grazianogrespan** [comment]
Thanks @manumaticx  for your reply ! 
I have to use this module cause i make changes to actionbar at runtime. Every window of my app has a different actionbar title,bg-color etc. 
Anyway thank you very much for the explanation!

**Comment by manumaticx** [comment]
You can use themes for this anyway.
Am 16.10.2015 6:20 nachm. schrieb "Graziano" <notifications@github.com>:

**Comment by manumaticx** [comment]
You can set window.title and window.theme before opening it. This will solve the delay issue. Use abx to change the background color *after* the window was opened.

**Comment by manumaticx** [comment]
Can we close this?

**Comment by grazianogrespan** [comment]
Yes @manumaticx , thank you again! ;)

**Comment by manumaticx** [comment]
:v:
